<div class="row">
    <div class="col-md">

        <iframe  id="spin-to-win-id" src="<?= $block->getUrl('spintowin/index/index') ?>"  
                 width="<?= $this->getData('width') ?>" 
                 height="<?= $this->getData('height') ?>"  ></iframe>

    </div>
    <div  class="col-md">
        <div id="spintowin-msg-box"></div>
        <div id="spintowin-board-one-box"></div>        
    </div>
</div>
